name: cryoforge-dev
channels:
  - conda-forge
dependencies:
  - python=3.13
  - xarray
  - awscli
  - dask[complete]
  - distributed=2025.5.0
  - jq
  - stac-geoparquet
  - pyarrow
  - obstore
  - arro3-core
  - rustac
  - python-duckdb
  - earthaccess
  - virtualizarr
  - kerchunk
  - jupyterlab<=4.2
  - dask-labextension
  - rioxarray
  - h3-py
  - tenacity
  - pyproj
  - h5netcdf
  - pystac
  - geojson
  - shapely
  - libstdcxx-ng
  - pytest
  - coiled
  - ruff
  - pip
