name: cryoforge
channels:
  - conda-forge
dependencies:
  - python=3.13
  - xarray
  - awscli
  - dask[complete]
  - distributed
  - jq
  - stac-geoparquet
  - fastparquet
  - pyarrow
  - obstore
  - rustac
  - python-duckdb
  - earthaccess
  - virtualizarr
  - kerchunk
  - jupyterlab
  - rioxarray
  - tenacity
  - pyproj
  - h5netcdf
  - pystac
  - geojson
  - shapely
  - libstdcxx-ng
  - pytest
  - coiled
  - ruff
  - mypy
  - pip
